name: Run Puppeteer Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  puppeteer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install Dependencies
        run: npm install

      - name: Install Puppeteer browsers
        run: npm run install-puppeteer-browser

      - name: Run Puppeteer Script
        run: node data.js
