name: Run Puppeteer Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  puppeteer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install Dependencies
        run: npm ci

      - name: Set Puppeteer cache directory permissions
        run: |
          sudo mkdir -p /usr/local/share/puppeteer-cache
          sudo chmod -R 777 /usr/local/share/puppeteer-cache

      - name: Install Puppeteer browsers
        env:
          PUPPETEER_CACHE_DIR: /usr/local/share/puppeteer-cache
        run: npx puppeteer browsers install chrome

      - name: Run Puppeteer Script
        run: node data.js
